# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 开放笔记
description: > # this means to ignore newlines until "baseurl:"
  记录生活、学习和思考
url: "https://goooooouwa.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

permalink: /:slugified_categories/:year/:month/:day/:slug:output_ext

collections:
  wiki:
    output: true

defaults:
  - scope:
      path: ""
      type: "wiki"
    values:
      layout: "post"
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - scripts/
  - README.md

include: [".well-known", ".nojekyll"]

# Build settings
markdown: kramdown

# Theme settings for minima

theme: minima

author:
  name: 徐顺发
  email: gouwa5700 (at) gmail (dot) com

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/goooooouwa" }
    - { platform: twitter, user_url: "https://twitter.com/Goooooouwa" }

show_excerpts: false

# disqus:
#  shortname: goooooouwa

google_analytics: G-669F0VG7BL

header_pages:
  - categories.html
  - tags.html
  - wiki.html
  - docs.html
  - about.md

# Plugin settings

pagination:
  enabled: true
  per_page: 10
  sort_reverse: true

autopages:
  enabled: true

jekyll-archives:
  enabled:
    - year
    - month
    - day
    - categories
    - tags
  layouts:
    year: year
    month: month
    day: day
    category: category
    tag: tag

google_custom_engine: 001725026263712877590:9lrhbwyoknb

jekyll_compose:
  auto_open: true
