version: '3'
volumes:
  static_files: {}

services:
  jekyllbuild:
    build:
      context: .
    volumes:
      - static_files:/build

  nginx:
    image: linuxserver/nginx:latest
    container_name: nginx4jekyll
    environment:
      - PUID=1024
      - PGID=100
      - TZ=Asia/Chongqing
    volumes:
      - static_files:/var/www/public
      - /home/admin/containers/jekyll/nginx/config:/config"
      - /etc/certs:/etc/certs
    ports:
      - 8743:443
    restart: unless-stopped
