version: '3'
volumes:
  static_files:
    driver_opts:
      type: tmpfs
      device: tmpfs

services:
  jekyllbuild:
    build:
      progress: plain
      context: .
      dockerfile: ./docker/jekyllbuild/Dockerfile
    volumes:
      - static_files:/srv/jekyll/_site
    ports:
      - 4000:4000

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx4jekyll
    environment:
      - PUID=1024
      - PGID=100
      - TZ=Asia/Chongqing
    volumes:
      - static_files:/var/www/public
      - /etc/certs:/etc/certs
    ports:
      - 8743:443
    restart: unless-stopped
