version: '3'
volumes:
  static_files: {}

services:
  jekyllbuild:
    build:
      context: .
    volumes:
      - static_files:/srv/jekyll/build

  nginx:
    image: linuxserver/nginx:latest
    container_name: nginx4jekyll
    environment:
      - PUID=1024
      - PGID=100
      - TZ=Asia/Chongqing
    volumes:
      - static_files:/var/www/public
      - ./nginx.conf:/config/nginx/site-confs/default.conf
      - /etc/certs:/etc/certs
    depends_on:
      - jekyllbuild
    ports:
      - 8743:443
    restart: unless-stopped
